diff a/drivers/misc/Makefile b/drivers/misc/Makefile	(rejected hunks)
@@ -59,4 +59,5 @@ obj-$(CONFIG_OMAP_DIE_TEMP_SENSOR)	+= omap_temp_sensor.o
 obj-$(CONFIG_LEDS_AN30259A)	+= leds-an30259a.o
 obj-$(CONFIG_COLOR_CONTROL)	+= color_control.o
 obj-$(CONFIG_CUSTOM_VOLTAGE)	+= custom_voltage.o
-obj-$(CONFIG_BLX)    += blx.o
\ No newline at end of file
+obj-$(CONFIG_BLX)    += blx.o
+obj-y				+= sound_control.o
