diff a/drivers/misc/Makefile b/drivers/misc/Makefile	(rejected hunks)
@@ -58,3 +58,4 @@ obj-$(CONFIG_SEC_MODEM)		+= modem_if/
 obj-$(CONFIG_USB_SWITCH_FSA9480)	+= fsa9480.o
 obj-$(CONFIG_OMAP_DIE_TEMP_SENSOR)	+= omap_temp_sensor.o
 obj-$(CONFIG_LEDS_AN30259A)	+= leds-an30259a.o
+obj-$(CONFIG_FSYNC_CONTROL)	+= fsync_control.o
