diff a/drivers/cpufreq/Makefile b/drivers/cpufreq/Makefile	(rejected hunks)
@@ -13,6 +13,18 @@ obj-$(CONFIG_CPU_FREQ_GOV_INTERACTIVE)	+= cpufreq_interactive.o
 obj-$(CONFIG_CPU_FREQ_GOV_HOTPLUG)	+= cpufreq_hotplug.o
 ## LGE_SJIT 2012-02-01 [dojip.kim@lge.com] Add sanjose governor
 obj-$(CONFIG_CPU_FREQ_GOV_SANJOSE)	+= cpufreq_sanjose.o
+obj-$(CONFIG_CPU_FREQ_GOV_LAZY)          += cpufreq_lazy.o
+obj-$(CONFIG_CPU_FREQ_GOV_WHEATLEY)  += cpufreq_wheatley.o
+obj-$(CONFIG_CPU_FREQ_GOV_PEGASUSQ)  += cpufreq_pegasusq.o
+obj-$(CONFIG_CPU_FREQ_GOV_AGGRESSIVE)  += cpufreq_aggressive.o
+obj-$(CONFIG_CPU_FREQ_GOV_GALLIMAUFRY)  += cpufreq_gallimaufry.o
+obj-$(CONFIG_CPU_FREQ_GOV_SAKURACTIVE)  += cpufreq_sakuractive.o
+obj-$(CONFIG_CPU_FREQ_GOV_SMARTASS2)  += cpufreq_smartass2.o
+obj-$(CONFIG_CPU_FREQ_GOV_INTERACTIVEX)  += cpufreq_interactiveX.o
+obj-$(CONFIG_CPU_FREQ_GOV_AGGRESSIVEX)  += cpufreq_aggressiveX.o
+obj-$(CONFIG_CPU_FREQ_GOV_GALLIMAUFRYX)  += cpufreq_gallimaufryX.o
+obj-$(CONFIG_CPU_FREQ_GOV_ADAPTIVE)     += cpufreq_adaptive.o
+obj-$(CONFIG_CPU_FREQ_GOV_LULZACTIVE)  += cpufreq_lulzactive.o
 
 # CPUfreq cross-arch helpers
 obj-$(CONFIG_CPU_FREQ_TABLE)		+= freq_table.o
